### ISSUE TITLE
Secret "resource-locker-operator-certs" not found

### ISSUE THREAD

**Issue by megian** [projectsyn/component-resource-locker#27]
After upgrading to version 2.3.0 the secret resource-locker-operator-certs was missing. I think this has been introduced in the helm chart 1.1.0.

## Steps to Reproduce the Problem
  1. Having a resource-locker component version v2.x
  1. Upgrade to v2.3.x

## Actual Behavior
```
  Warning  FailedMount  2m1s (x11 over 8m13s)  kubelet            MountVolume.SetUp failed for volume "tls-cert" : secret "resource-locker-operator-certs" not found
  Warning  FailedMount  99s (x3 over 6m10s)    kubelet            Unable to attach or mount volumes: unmounted volumes=[tls-cert], unattached volumes=[tls-cert resource-locker-operator-controller-manager-token-2n7j7]: timed out waiting for the condition
```

## Expected Behavior
Operator pod should start

## Workaround
```
apiVersion: v1
kind: Secret
metadata:
  name: resource-locker-operator-certs
  namespace: syn-resource-locker
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""
```
